# -*- coding: utf-8 -*-
"""market_basket.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kp16GMML6Z1Dp8vCPF0lbT-U1ZlfYyol
"""

# !pip install mlxtend

import importlib
import pandas as pd
from mlxtend.frequent_patterns import apriori, association_rules
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)

# Load the dataset
# df = pd.read_csv('/kaggle/input/groceries-dataset-for-apriori-algorithm/groceries_dataset.csv')

df = pd.read_csv("Groceries_dataset.csv", delimiter=",")  # Try "," or ";" or "|"

df

df.describe

df.shape

df.notnull().sum()

df.isnull().sum()

#setting index as Date
df.set_index('Date',inplace = True)

df.head()

df.index=pd.to_datetime(df.index)

df.head()

#gathering information about products
total_item = len(df)
total_days = len(np.unique(df.index.date))
total_months = len(np.unique(df.index.year))
print(total_item,total_days,total_months)

plt.figure(figsize=(15,5))
sns.barplot(x = df.itemDescription.value_counts().head(20).index, y = df.itemDescription.value_counts().head(20).values, palette = 'gnuplot')
plt.xlabel('itemDescription', size = 15)
plt.xticks(rotation=45)
plt.ylabel('Count of Items', size = 15)
plt.title('Top 20 Items purchased by customers', color = 'green', size = 20)
plt.show()

df['itemDescription'].value_counts()

#grouping dataset to form a list of products bought by same customer on same date
df=df.groupby(['Member_number','Date'])['itemDescription'].apply(lambda x: list(x))

df.head(10)

#apriori takes list as an input, hence converting dtaset to a list
transactions = df.values.tolist()
transactions[:10]

!pip install apyori

#applying apriori
from apyori import apriori
rules = apriori(transactions, min_support=0.00030,min_confidence = 0.05,min_lift = 2,min_length = 2)
results = list(rules)
results

def inspect(results):
    lhs         = [tuple(result[2][0][0])[0] for result in results]
    rhs         = [tuple(result[2][0][1])[0] for result in results]
    supports    = [result[1] for result in results]
    confidences = [result[2][0][2] for result in results]
    lifts       = [result[2][0][3] for result in results]
    return list(zip(lhs, rhs, supports, confidences, lifts))
ordered_results = pd.DataFrame(inspect(results), columns = ['Left Hand Side', 'Right Hand Side', 'Support', 'Confidence', 'Lift'])